on:
  schedule:
    - cron: '30 23 */3 * *'
  workflow_dispatch:
    branches: [main, master]

name: scrape_vacina_mun

jobs:
  render:
    name: scrape_vacina_mun
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install package
        run: Rscript -e "pak::local_install('.')"

      - name: Create env file
        run: |
          touch ~/.Renviron
          echo SCRAP_URL=${{ secrets.SCRAP_URL }} >> ~/.Renviron
          echo SCRAP_USUARIO=${{ secrets.SCRAP_USUARIO }} >> ~/.Renviron
          echo SCRAP_SENHA=${{ secrets.SCRAP_SENHA }} >> ~/.Renviron

      - name: Execute Script
        run: Rscript "inst/scrape_vaccine.R"

      - name: Push files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add inst/base_vacina_mun.csv
          git commit -F mensagem-comit.txt || echo "No changes to commit"
          git push origin || echo "No changes to commit"
