on:
  schedule:
    - cron: '30 23 */3 * *'
  workflow_dispatch:
    branches: [main, master]

name: scrape_vacina_mun

jobs:
  render:
    name: scrape_vacina_mun
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SCRAP_URL: ${{ secrets.SCRAP_URL }}
      SCRAP_USUARIO: ${{ secrets.SCRAP_USUARIO }}
      SCRAP_SENHA: ${{ secrets.SCRAP_SENHA }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install package
        run: Rscript -e "pak::local_install('.')"

      - name: Execute Script
        run: Rscript "inst/scrape_vaccine.R"
