on:
  schedule:

    - cron:  '0 */6 * * *'
  workflow_dispatch:
    branches: [main, master]


name: scrape_vacina_mun

jobs:
  render:

    name: scrape_vacina_mun

    runs-on: ubuntu-18.04

    env:
      RSPM: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SCRAP_URL: ${{ secrets.SCRAP_URL }}
      SCRAP_USUARIO: ${{ secrets.SCRAP_USUARIO }}
      SCRAP_SENHA: ${{ secrets.SCRAP_SENHA }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: mostrar as variaveis
        run: |
          echo "a primeira e a url" ${{ env.SCRAP_URL}}"
          echo "a segunda e o usuario" ${{ env.SCRAP_USUARIO }}"
